---
version: '3'

services:
  consul-server:
    image: hashicorp/consul
    command: agent -bootstrap-expect=1 -ui -client=0.0.0.0
    ports:
      - 8500:8500
      - 8600:8600
      - 8301:8301
      - 8302:8302
      - '8600:8600/udp'

    volumes:
      - ./consul/config/server.json:/consul/config/server.json
    networks:
      - microservices-lab-network-consul
    environment:
      - NODE=consul-server

  consul-client-messages:
    image: hashicorp/consul
    command: agent -join=consul-server
    depends_on:
      - consul-server
      - messages-service-1
    volumes:
      - ./consul/config/messages.json:/consul/config/messages.json
    networks:
      - microservices-lab-network-consul

  consul-client-facade:
    image: hashicorp/consul
    command: agent -join=consul-server
    depends_on:
      - consul-server
      - facade-service
    volumes:
      - ./consul/config/facade.json:/consul/config/facade.json
    networks:
      - microservices-lab-network-consul

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - microservices-lab-network-consul

  facade-service:
    build: ./facade-service
    depends_on:
      - rabbitmq
      # - logging-service-1
      # - logging-service-2
      # - logging-service-3
      - messages-service-1
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - Q_NAME=common_msg
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MESSAGES_HOST=messages-service-1
      - MESSAGES_PORT=5002
      # - LOGGING_PORT_1=8080
      # - LOGGING_PORT_2=8081
      # - LOGGING_PORT_3=8082
      # - LOGGING_HOST_1=logging-service-1
      # - LOGGING_HOST_2=logging-service-2
      # - LOGGING_HOST_3=logging-service-3
    ports:
      - '5000:5000'
    networks:
      - microservices-lab-network-consul

  messages-service-1:
    build: ./messages-service
    # ports:
    #   - '5002:5002'
    depends_on:
      - rabbitmq
    environment:
      - PORT=5002
      - HOST=0.0.0.0
      - Q_NAME=common_msg
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - FACADE_HOST=facade-service
      - FACADE_PORT=5000
    networks:
      - microservices-lab-network-consul

networks:
  microservices-lab-network-consul:
    driver: bridge

volumes:
  app:
  # messages-service-2:
  #   build: ./messages-service

  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     - PORT=5002
  #     - HOST=0.0.0.0
  #     - Q_NAME=common_msg
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - FACADE_HOST=facade-service
  #     - FACADE_PORT=5000
  #   networks:
  #     - microservices-lab-network

  # messages-service-3:
  #   build: ./messages-service
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     - PORT=5002
  #     - HOST=0.0.0.0
  #     - Q_NAME=common_msg
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - FACADE_HOST=facade-service
  #     - FACADE_PORT=5000
  #   networks:
  #     - microservices-lab-network

  # balancer:
  #   image: haproxy
  #   depends_on:
  #     - messages-service-1
  #     - messages-service-2
  #     - messages-service-3
  #   volumes:
  #     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  #   networks:
  #     - microservices-lab-network

  # logging-service-1:
  #   build: ./LoggingService
  #   volumes:
  #     - app:/code
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     SERVER_PORT: 8080
  #     HAZELCAST_CONFIG: |
  #       <hazelcast>
  #         <network>
  #           <port>5701</port>
  #           <join>
  #             <multicast enabled="false" />
  #             <tcp-ip>
  #               <members>logging-service-1,logging-service-2,logging-service-3</members>
  #             </tcp-ip>
  #           </join>
  #         </network>
  #       </hazelcast>
  #   networks:
  #     - microservices-lab-network

  # logging-service-2:
  #   build: ./LoggingService
  #   volumes:
  #     - app:/code
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     SERVER_PORT: 8081
  #     HAZELCAST_CONFIG: |
  #       <hazelcast>
  #         <network>
  #           <port>5701</port>
  #           <join>
  #             <multicast enabled="false" />
  #             <tcp-ip>
  #               <members>logging-service-1,logging-service-2,logging-service-3</members>
  #             </tcp-ip>
  #           </join>
  #         </network>
  #       </hazelcast>
  #   networks:
  #     - microservices-lab-network

  # logging-service-3:
  #   build: ./LoggingService
  #   volumes:
  #     - app:/code
  #   ports:
  #     - '8082:8082'
  #   environment:
  #     SERVER_PORT: 8082
  #     HAZELCAST_CONFIG: |
  #       <hazelcast>
  #         <network>
  #           <port>5701</port>
  #           <join>
  #             <multicast enabled="false" />
  #             <tcp-ip>
  #               <members>logging-service-1,logging-service-2,logging-service-3</members>
  #             </tcp-ip>
  #           </join>
  #         </network>
  #       </hazelcast>
  #   networks:
  #     - microservices-lab-network
