---
version: '3'

services:
  facade-service:
    build: ./facade-service
    depends_on:
      - logging-service-1
      - logging-service-2
      - logging-service-3
      - messages-service
    environment:
      - HOST=0.0.0.0
      - LOGGING_PORT_1=8080
      - LOGGING_PORT_2=8081
      - LOGGING_PORT_3=8082
      - MESSAGES_PORT=5002
    ports:
      - '5000:5000'

  logging-service-1:
    build: ./LoggingService
    volumes:
      - app:/code
    ports:
      - '8080:8080'
    environment:
      SERVER_PORT: 8080
      HAZELCAST_CONFIG: |
        <hazelcast>
          <network>
            <port>5701</port>
            <join>
              <multicast enabled="false" />
              <tcp-ip>
                <members>logging-service-1,logging-service-2,logging-service-3</members>
              </tcp-ip>
            </join>
          </network>
        </hazelcast>

  logging-service-2:
    build: ./LoggingService
    volumes:
      - app:/code
    ports:
      - '8081:8081'
    environment:
      SERVER_PORT: 8081
      HAZELCAST_CONFIG: |
        <hazelcast>
          <network>
            <port>5701</port>
            <join>
              <multicast enabled="false" />
              <tcp-ip>
                <members>logging-service-1,logging-service-2,logging-service-3</members>
              </tcp-ip>
            </join>
          </network>
        </hazelcast>

  logging-service-3:
    build: ./LoggingService
    volumes:
      - app:/code
    ports:
      - '8082:8082'
    environment:
      SERVER_PORT: 8082
      HAZELCAST_CONFIG: |
        <hazelcast>
          <network>
            <port>5701</port>
            <join>
              <multicast enabled="false" />
              <tcp-ip>
                <members>logging-service-1,logging-service-2,logging-service-3</members>
              </tcp-ip>
            </join>
          </network>
        </hazelcast>

  messages-service:
    build: ./messages-service
    ports:
      - '5002:5002'

volumes:
  app:
