---
version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    # ports:
    #   - '5672:5672'
    #   - '15672:15672'
    networks:
      - microservices-lab-network

  facade-service:
    build: ./facade-service
    depends_on:
      - rabbitmq
      - logging-service-1
      - logging-service-2
      - logging-service-3
      - balancer
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - Q_NAME=common_msg
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MESSAGES_HOST=balancer
      - MESSAGES_PORT=5002
      - LOGGING_PORT_1=8080
      - LOGGING_PORT_2=8081
      - LOGGING_PORT_3=8082
      - LOGGING_HOST_1=logging-service-1
      - LOGGING_HOST_2=logging-service-2
      - LOGGING_HOST_3=logging-service-3
    ports:
      - '5000:5000'
    networks:
      - microservices-lab-network

  messages-service-1:
    build: ./messages-service
    # ports:
    #   - '5002:5002'
    depends_on:
      - rabbitmq
    environment:
      - PORT=5002
      - HOST=0.0.0.0
      - Q_NAME=common_msg
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - FACADE_HOST=facade-service
      - FACADE_PORT=5000
    networks:
      - microservices-lab-network

  messages-service-2:
    build: ./messages-service

    depends_on:
      - rabbitmq
    environment:
      - PORT=5002
      - HOST=0.0.0.0
      - Q_NAME=common_msg
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - FACADE_HOST=facade-service
      - FACADE_PORT=5000
    networks:
      - microservices-lab-network

  messages-service-3:
    build: ./messages-service
    depends_on:
      - rabbitmq
    environment:
      - PORT=5002
      - HOST=0.0.0.0
      - Q_NAME=common_msg
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - FACADE_HOST=facade-service
      - FACADE_PORT=5000
    networks:
      - microservices-lab-network

  balancer:
    image: haproxy
    depends_on:
      - messages-service-1
      - messages-service-2
      - messages-service-3
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - microservices-lab-network

  logging-service-1:
    build: ./LoggingService
    volumes:
      - app:/code
    ports:
      - '8080:8080'
    environment:
      SERVER_PORT: 8080
      HAZELCAST_CONFIG: |
        <hazelcast>
          <network>
            <port>5701</port>
            <join>
              <multicast enabled="false" />
              <tcp-ip>
                <members>logging-service-1,logging-service-2,logging-service-3</members>
              </tcp-ip>
            </join>
          </network>
        </hazelcast>
    networks:
      - microservices-lab-network

  logging-service-2:
    build: ./LoggingService
    volumes:
      - app:/code
    ports:
      - '8081:8081'
    environment:
      SERVER_PORT: 8081
      HAZELCAST_CONFIG: |
        <hazelcast>
          <network>
            <port>5701</port>
            <join>
              <multicast enabled="false" />
              <tcp-ip>
                <members>logging-service-1,logging-service-2,logging-service-3</members>
              </tcp-ip>
            </join>
          </network>
        </hazelcast>
    networks:
      - microservices-lab-network

  logging-service-3:
    build: ./LoggingService
    volumes:
      - app:/code
    ports:
      - '8082:8082'
    environment:
      SERVER_PORT: 8082
      HAZELCAST_CONFIG: |
        <hazelcast>
          <network>
            <port>5701</port>
            <join>
              <multicast enabled="false" />
              <tcp-ip>
                <members>logging-service-1,logging-service-2,logging-service-3</members>
              </tcp-ip>
            </join>
          </network>
        </hazelcast>
    networks:
      - microservices-lab-network

networks:
  microservices-lab-network:
    driver: bridge

volumes:
  app:
