---
version: '3'

services:
  consul-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    networks:
      - microservices-lab-network-consul

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - microservices-lab-network-consul

  facade-service:
    build: ./facade-service
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq
      - consul-server
      - messages-service-1
      - messages-service-2
      - messages-service-3
    environment:
      - PORT=5000
      - APP_NAME=facadeService
      - RABBITMQ_HOST=rabbitmq
      - LS1_PORT=8080
      - LS2_PORT=8081
      - LS3_PORT=8082
    networks:
      - microservices-lab-network-consul

  messages-service-1:
    build: ./messages-service
    depends_on:
      - rabbitmq
      - consul-server
    environment:
      - PORT=5002
      - APP_NAME=messagesService
      - MY_INDEX=1
      - RABBITMQ_HOST=rabbitmq
    networks:
      - microservices-lab-network-consul

  messages-service-2:
    build: ./messages-service
    depends_on:
      - rabbitmq
      - consul-server
    environment:
      - PORT=5003
      - APP_NAME=messagesService
      - MY_INDEX=2
      - RABBITMQ_HOST=rabbitmq
    networks:
      - microservices-lab-network-consul

  messages-service-3:
    build: ./messages-service
    depends_on:
      - rabbitmq
      - consul-server
    environment:
      - PORT=5004
      - APP_NAME=messagesService
      - MY_INDEX=3
      - RABBITMQ_HOST=rabbitmq
    networks:
      - microservices-lab-network-consul

  logging-service-1:
    build: ./LoggingService
    volumes:
      - app:/code
    ports:
      - '8080:8080'
    environment:
      SERVER_PORT: 8080
      HAZELCAST_CONFIG: |
        <hazelcast>
          <network>
            <port>5701</port>
            <join>
              <multicast enabled="false" />
              <tcp-ip>
                <members>logging-service-1,logging-service-2,logging-service-3</members>
              </tcp-ip>
            </join>
          </network>
        </hazelcast>
    networks:
      - microservices-lab-network-consul

  logging-service-2:
    build: ./LoggingService
    volumes:
      - app:/code
    ports:
      - '8081:8081'
    environment:
      SERVER_PORT: 8081
      HAZELCAST_CONFIG: |
        <hazelcast>
          <network>
            <port>5701</port>
            <join>
              <multicast enabled="false" />
              <tcp-ip>
                <members>logging-service-1,logging-service-2,logging-service-3</members>
              </tcp-ip>
            </join>
          </network>
        </hazelcast>
    networks:
      - microservices-lab-network-consul

  logging-service-3:
    build: ./LoggingService
    volumes:
      - app:/code
    ports:
      - '8082:8082'
    environment:
      SERVER_PORT: 8082
      HAZELCAST_CONFIG: |
        <hazelcast>
          <network>
            <port>5701</port>
            <join>
              <multicast enabled="false" />
              <tcp-ip>
                <members>logging-service-1,logging-service-2,logging-service-3</members>
              </tcp-ip>
            </join>
          </network>
        </hazelcast>
    networks:
      - microservices-lab-network-consul
networks:
  microservices-lab-network-consul:
    driver: bridge
volumes:
  app:
